<?php

namespace AppBundle\Repository;

/**
 * ClassRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
