<?php

namespace AppBundle\Repository;

/**
 * ClassSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassSubjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function isAlreadyCreated($subject, $class)
    {
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.subject = :subject')
            ->andWhere('s.cClass = :class')
            ->orderBy('s.id', 'ASC')
            ->setMaxResults(1)
            ->setParameter('subject', $subject)
            ->setParameter('class', $class)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
