<?php

namespace AppBundle\Repository;

/**
 * CodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeRepository extends \Doctrine\ORM\EntityRepository
{
     public function getRandomCodes($amount)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->andWhere('c.status = :virgin')
            ->setParameter('virgin', 'virgin')
            ->getQuery()
            ->setMaxResults($amount)
            ->getResult();
    }
}
