<?php

namespace AppBundle\Repository;

/**
 * LessonDurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonDurationRepository extends \Doctrine\ORM\EntityRepository
{
}
