<?php

namespace AppBundle\Repository;

/**
 * SchoolDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
