<?php

namespace AppBundle\Repository;

/**
 * TimetablerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetablerRepository extends \Doctrine\ORM\EntityRepository
{
}
